#A tuple with 5 numbers using parentheses.
tup1 = (1, 2, 3, 4, 5)
print("Tuple 1 = ",tup1)
print(type(tup1))

# A mixed tuple containing integer, string, float, and boolean.
tup2 = (18, "Samiksha", 5.12, True)
print("Tuple 2 = ",tup2)
print(type(tup1))

#An empty tuple using two different ways.
tup3 = ()
print("tuple 3 = ",tup3)
print(type(tup1))

#A single-element tuple with the value 99.
tup4 = (99,)
print("Tuple 4 = ",tup4)
print(type(tup4))
