#A set with 5 integers.
st1 = {1 , 2 , 3 , 4 , 5}
print("Set 1 = ",st1)
print(type(st1))

#b) A set with mixed data types (integer, string, float).
st2 = {12,"Samiksha",84.85}
print("Sst 2 = ",st2)
print(type(st2))

#c) An empty set using the correct method.
st3 = set()
print("Set 3 = ",st3)
print(type(st3))

#d) A set from the string "hello" using the set() constructor.
st4 = set("Hello")
print("Set 4 = ",st4)
print(type(st4))